// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoOzMCmnqUVS9_9evt6saJ3VIjIPJp81Y',
    appId: '1:1046147688836:web:dbb47c5bee7712a87715d1',
    messagingSenderId: '1046147688836',
    projectId: 'wvrmhat-mynotes',
    authDomain: 'wvrmhat-mynotes.firebaseapp.com',
    storageBucket: 'wvrmhat-mynotes.appspot.com',
    measurementId: 'G-RV6WHRLLEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GSvdVxRuJPf4TOqL2_6SOSkhG6TQFZc',
    appId: '1:1046147688836:android:f0f89cad4635299e7715d1',
    messagingSenderId: '1046147688836',
    projectId: 'wvrmhat-mynotes',
    storageBucket: 'wvrmhat-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJH7Rhw4gVXTGCw2jZYRvpEYC-LJfYHNw',
    appId: '1:1046147688836:ios:1c617d6c777857417715d1',
    messagingSenderId: '1046147688836',
    projectId: 'wvrmhat-mynotes',
    storageBucket: 'wvrmhat-mynotes.appspot.com',
    iosBundleId: 'com.fluttertut.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJH7Rhw4gVXTGCw2jZYRvpEYC-LJfYHNw',
    appId: '1:1046147688836:ios:1c617d6c777857417715d1',
    messagingSenderId: '1046147688836',
    projectId: 'wvrmhat-mynotes',
    storageBucket: 'wvrmhat-mynotes.appspot.com',
    iosBundleId: 'com.fluttertut.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoOzMCmnqUVS9_9evt6saJ3VIjIPJp81Y',
    appId: '1:1046147688836:web:6196c2db7893519f7715d1',
    messagingSenderId: '1046147688836',
    projectId: 'wvrmhat-mynotes',
    authDomain: 'wvrmhat-mynotes.firebaseapp.com',
    storageBucket: 'wvrmhat-mynotes.appspot.com',
    measurementId: 'G-C0MTS2LQ4R',
  );
}
